services:
  server:
    image: softvence/juan-server:latest
    container_name: juan-server
    platform: linux/amd64
    profiles:
      - prod
      - server
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9000:${PORT:-9000}"
    env_file:
      - .env
    volumes:
      - ./uploads:/app/uploads
      - ./logs:/app/logs
    networks:
      - juan-network
  database:
    image: postgres:latest
    container_name: juan-database
    restart: always
    profiles:
      - dev
      - prod
      - database
    ports:
      - 5431:5432
    environment:
      - POSTGRES_USER=${DB_USER:-postgres}
      - POSTGRES_PASSWORD=${DB_PASSWORD:-postgres}
      - POSTGRES_DB=${DB_NAME:-juan}
    volumes:
      - postgres_data:/var/lib/postgresql
    networks:
      - juan-network
  elasticsearch:
    image: elasticsearch:9.3.1
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
      - ELASTIC_USERNAME=${ES_USERNAME:-elastic}
      - ELASTIC_PASSWORD=${ES_PASSWORD:-elastic}
    profiles:
      - dev
      - prod
      - elasticsearch
    ports:
      - "9200:9200"
    volumes:
      - elasticsearch:/usr/share/elasticsearch/data
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl -fs http://localhost:9200/_cluster/health?wait_for_status=yellow&timeout=1s || exit 1",
        ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 40s
    restart: unless-stopped
    networks:
      - juan-network
networks:
  juan-network:
    driver: bridge
volumes:
  postgres_data:
  elasticsearch:
