basePath: /
definitions:
  github_com_devlopersabbir_juan_don82-server_api_chat_core.ChatRoom:
    properties:
      agent_id:
        type: integer
      created_at:
        type: string
      id:
        type: integer
      property_id:
        description: Negotiation with reference to property
        type: integer
      user_id:
        type: integer
    type: object
  github_com_devlopersabbir_juan_don82-server_api_chat_core.Message:
    properties:
      content:
        type: string
      created_at:
        type: string
      id:
        type: integer
      room_id:
        type: integer
      sender_id:
        type: integer
    type: object
  github_com_devlopersabbir_juan_don82-server_api_chat_domain.CreateRoomRequest:
    properties:
      agent_id:
        type: integer
      property_id:
        type: integer
    required:
    - agent_id
    - property_id
    type: object
  github_com_devlopersabbir_juan_don82-server_api_chat_domain.SendMessageRequest:
    properties:
      content:
        type: string
      room_id:
        type: integer
    required:
    - content
    - room_id
    type: object
  github_com_devlopersabbir_juan_don82-server_api_property_domain.PropertyRequest:
    properties:
      address:
        type: string
      bathrooms:
        type: integer
      bedrooms:
        type: integer
      city:
        type: string
      country:
        type: string
      description:
        type: string
      discount_price:
        type: number
      images:
        items:
          type: string
        type: array
      name:
        type: string
      price:
        type: number
      property_type:
        enum:
        - SELL
        - RENT
        type: string
      rent_period:
        enum:
        - YEARLY
        - MONTHLY
        type: string
      square_feet:
        type: integer
      state:
        type: string
      status:
        type: string
      videos:
        items:
          type: string
        type: array
      zip_code:
        type: string
    required:
    - address
    - bathrooms
    - bedrooms
    - city
    - country
    - description
    - images
    - name
    - price
    - property_type
    - square_feet
    - state
    - status
    - zip_code
    type: object
  github_com_devlopersabbir_juan_don82-server_api_subscriptions_core.SubscriptionPlan:
    properties:
      duration_days:
        type: integer
      id:
        type: integer
      name:
        type: string
      price:
        type: number
      property_limit:
        type: integer
    type: object
  github_com_devlopersabbir_juan_don82-server_api_subscriptions_domain.PurchaseSubscriptionRequest:
    properties:
      plan_id:
        type: integer
    required:
    - plan_id
    type: object
  github_com_devlopersabbir_juan_don82-server_api_users_domain.AuthResponse:
    properties:
      access_token:
        type: string
      refresh_token:
        type: string
    type: object
  github_com_devlopersabbir_juan_don82-server_api_users_domain.CreateUserRequest:
    properties:
      email:
        maxLength: 255
        minLength: 3
        type: string
      name:
        maxLength: 255
        minLength: 3
        type: string
      password:
        maxLength: 255
        minLength: 3
        type: string
    required:
    - email
    - name
    - password
    type: object
  github_com_devlopersabbir_juan_don82-server_api_users_domain.LoginRequest:
    properties:
      email:
        type: string
      password:
        type: string
    required:
    - email
    - password
    type: object
  github_com_devlopersabbir_juan_don82-server_api_users_domain.RefreshRequest:
    properties:
      refresh_token:
        type: string
    required:
    - refresh_token
    type: object
host: localhost:9000
info:
  contact: {}
  description: Modern REST API for Juan Don project
  title: Juan Don API
  version: "1.0"
paths:
  /api/v1/admin/chats:
    get:
      description: Admin can fetch all chat rooms
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items: {}
            type: array
      security:
      - BearerAuth: []
      summary: Get all chats
      tags:
      - Admin
  /api/v1/admin/properties:
    get:
      description: Admin can fetch all properties
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items: {}
            type: array
      security:
      - BearerAuth: []
      summary: Get all properties
      tags:
      - Admin
  /api/v1/admin/users:
    get:
      description: Admin can fetch all users and agents
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items: {}
            type: array
      security:
      - BearerAuth: []
      summary: Get all users
      tags:
      - Admin
  /api/v1/auth/login:
    post:
      consumes:
      - application/json
      description: Authenticates a user and returns access and refresh
      parameters:
      - description: Login Credentials
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/github_com_devlopersabbir_juan_don82-server_api_users_domain.LoginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: Tokens
          schema:
            $ref: '#/definitions/github_com_devlopersabbir_juan_don82-server_api_users_domain.AuthResponse'
      summary: Log in a user
      tags:
      - Authentication
  /api/v1/auth/refresh:
    post:
      consumes:
      - application/json
      description: Provides a new access token using a refresh token
      parameters:
      - description: Refresh Token
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/github_com_devlopersabbir_juan_don82-server_api_users_domain.RefreshRequest'
      produces:
      - application/json
      responses:
        "200":
          description: New tokens
          schema:
            $ref: '#/definitions/github_com_devlopersabbir_juan_don82-server_api_users_domain.AuthResponse'
      summary: Refresh authentication token
      tags:
      - Authentication
  /api/v1/auth/register:
    post:
      consumes:
      - application/json
      description: Creates a new user with name, email, and password
      parameters:
      - description: User Registration Details
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/github_com_devlopersabbir_juan_don82-server_api_users_domain.CreateUserRequest'
      produces:
      - application/json
      responses:
        "201":
          description: User created successfully
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Register a new user
      tags:
      - Authentication
  /api/v1/chats/message:
    post:
      consumes:
      - application/json
      description: Sends a message to a specific chat room
      parameters:
      - description: Message Content
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/github_com_devlopersabbir_juan_don82-server_api_chat_domain.SendMessageRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/github_com_devlopersabbir_juan_don82-server_api_chat_core.Message'
      security:
      - BearerAuth: []
      summary: Send a message
      tags:
      - Chat
  /api/v1/chats/start:
    post:
      consumes:
      - application/json
      description: Creates a new chat room or returns existing one for a specific
        property
      parameters:
      - description: Chat Details
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/github_com_devlopersabbir_juan_don82-server_api_chat_domain.CreateRoomRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/github_com_devlopersabbir_juan_don82-server_api_chat_core.ChatRoom'
      security:
      - BearerAuth: []
      summary: Start a chat with an agent
      tags:
      - Chat
  /api/v1/properties:
    get:
      description: Fetches a list of all properties
      produces:
      - application/json
      responses:
        "200":
          description: List of properties
          schema:
            additionalProperties: true
            type: object
      summary: Get all properties
      tags:
      - Properties
    post:
      consumes:
      - application/json
      description: Creates a new property (Only for AGENT and SYSTEM_ADMIN)
      parameters:
      - description: Property Details
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/github_com_devlopersabbir_juan_don82-server_api_property_domain.PropertyRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Property created successfully
          schema:
            additionalProperties: true
            type: object
      security:
      - BearerAuth: []
      summary: Create a property
      tags:
      - Properties
  /api/v1/properties/{id}:
    delete:
      description: Deletes a property by its ID
      parameters:
      - description: Property ID
        in: path
        name: id
        required: true
        type: integer
      responses:
        "200":
          description: Property deleted successfully
          schema:
            additionalProperties: true
            type: object
      security:
      - BearerAuth: []
      summary: Delete a property
      tags:
      - Properties
    get:
      description: Fetches a single property by its ID
      parameters:
      - description: Property ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: Property details
          schema:
            additionalProperties: true
            type: object
      summary: Get a property
      tags:
      - Properties
    put:
      consumes:
      - application/json
      description: Updates an existing property by its ID
      parameters:
      - description: Property ID
        in: path
        name: id
        required: true
        type: integer
      - description: Property Details
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/github_com_devlopersabbir_juan_don82-server_api_property_domain.PropertyRequest'
      produces:
      - application/json
      responses:
        "200":
          description: Property updated successfully
          schema:
            additionalProperties: true
            type: object
      security:
      - BearerAuth: []
      summary: Update a property
      tags:
      - Properties
  /api/v1/subscriptions/plans:
    get:
      description: Fetches a list of all available subscription plans
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/github_com_devlopersabbir_juan_don82-server_api_subscriptions_core.SubscriptionPlan'
            type: array
      summary: Get all subscription plans
      tags:
      - Subscriptions
  /api/v1/subscriptions/purchase:
    post:
      consumes:
      - application/json
      description: Allows an agent to purchase a subscription plan
      parameters:
      - description: Purchase Details
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/github_com_devlopersabbir_juan_don82-server_api_subscriptions_domain.PurchaseSubscriptionRequest'
      produces:
      - application/json
      responses:
        "200":
          description: Subscription purchased successfully
          schema:
            additionalProperties:
              type: string
            type: object
      security:
      - BearerAuth: []
      summary: Purchase a subscription plan
      tags:
      - Subscriptions
  /api/v1/users:
    get:
      description: Fetches a list of all users. Requires authentication.
      produces:
      - application/json
      responses:
        "200":
          description: Users fetched successfully
          schema:
            additionalProperties:
              type: string
            type: object
      security:
      - BearerAuth: []
      summary: Get all users
      tags:
      - Users
securityDefinitions:
  BearerAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
